---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-docker-k8s-service-secret
stringData:
  MYSQL_ROOT_PASSWORD: "Irpgamerbr_17"
  MYSQL_USER: "devicaro"
  MYSQL_PASSWORD: "Irpgamerbr_17"
  MYSQL_DATABASE: "mysql_docker_k8s_service_database"
  MYSQL_PORT: "3306"
  MYSQL_ROOT_HOST: "localhost"