---
apiVersion: v1
kind: Service
metadata:
  name: mysql-docker-k8s-service
spec:
  selector:
    app: mysql-docker-k8s-service
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP