---
apiVersion: v1
kind: Service
metadata:
  name: dockerize-xapp-nginx-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "3"
    service.beta.kubernetes.io/linode-loadbalancer-default-protocol: "tcp"
  labels:
    app: nginx-docker-k8s-service
spec:
  selector:
    app: nginx-docker-k8s-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: LoadBalancer
  sessionAffinity: None