---
apiVersion: v1
kind: Service
metadata:
  name: php-docker-k8s-service
spec:
  selector:
    app: php-docker-k8s-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP