---
apiVersion: v1
kind: Service
metadata:
  name: redis-docker-k8s-service
spec:
  selector:
    app: redis-docker-k8s-service
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP