name: CI-CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: |
          cd services/web/php
          composer validate --strict

      - name: Install dependencies
        run: |
          cd services/web/php
          composer install --prefer-dist --no-interaction --no-progress

  cd:
    runs-on: ubuntu-latest
    needs: ci
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        timeout-minutes: 5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.XTOKEN }}
        timeout-minutes: 5

      - name: Set GHCR image name
        run: echo "IMAGE_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build services/PHP Docker image
        run: |
          cd services/web/php
          docker build -t php-docker-k8s-image:v1 .
        timeout-minutes: 5

      - name: Push services/PHP Docker image to Docker Hub
        run: |
          docker tag php-docker-k8s-image:v1 ${{ secrets.DOCKER_USERNAME }}/php-docker-k8s-image:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/php-docker-k8s-image:v1

        timeout-minutes: 5

      - name: Push services/PHP Docker image to GHCR
        run: |
          docker tag php-docker-k8s-image:v1 ghcr.io/${{ env.IMAGE_OWNER }}/php-docker-k8s-image:v1
          docker push ghcr.io/${{ env.IMAGE_OWNER }}/php-docker-k8s-image:v1
        timeout-minutes: 5

      - name: Build services/Nginx Docker image
        run: |
          cd services/web/nginx
          docker build -t nginx-docker-k8s-image:v1 .
        timeout-minutes: 5

      - name: Push services/Nginx Docker image to Docker Hub
        run: |
          docker tag nginx-docker-k8s-image:v1 ${{ secrets.DOCKER_USERNAME }}/nginx-docker-k8s-image:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-docker-k8s-image:v1
        timeout-minutes: 5

      - name: Push services/Nginx Docker image to GHCR
        run: |
          docker tag nginx-docker-k8s-image:v1 ghcr.io/${{ env.IMAGE_OWNER }}/nginx-docker-k8s-image:v1
          docker push ghcr.io/${{ env.IMAGE_OWNER }}/nginx-docker-k8s-image:v1
        timeout-minutes: 5

      - name: Build services/mysql Docker image
        run: |
          cd services/database/mysql
          docker build -t mysql-docker-k8s-image:v1 .
        timeout-minutes: 5

      - name: Push services/mysql Docker image to Docker Hub
        run: |
          docker tag mysql-docker-k8s-image:v1 ${{ secrets.DOCKER_USERNAME }}/mysql-docker-k8s-image:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/mysql-docker-k8s-image:v1
        timeout-minutes: 5

      - name: Push services/mysql Docker image to GHCR
        run: |
          docker tag mysql-docker-k8s-image:v1 ghcr.io/${{ env.IMAGE_OWNER }}/mysql-docker-k8s-image:v1
          docker push ghcr.io/${{ env.IMAGE_OWNER }}/mysql-docker-k8s-image:v1
        timeout-minutes: 5

      - name: Build services/redis Docker image
        run: |
          cd services/database/redis
          docker build -t redis-docker-k8s-image:v1 .
        timeout-minutes: 5

      - name: Push services/redis Docker image to Docker Hub
        run: |
          docker tag redis-docker-k8s-image:v1 ${{ secrets.DOCKER_USERNAME }}/redis-docker-k8s-image:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/redis-docker-k8s-image:v1
        timeout-minutes: 5

      - name: Push services/redis Docker image to GHCR
        run: |
          docker tag redis-docker-k8s-image:v1 ghcr.io/${{ env.IMAGE_OWNER }}/redis-docker-k8s-image:v1
          docker push ghcr.io/${{ env.IMAGE_OWNER }}/redis-docker-k8s-image:v1
        timeout-minutes: 5